enum USERSTATUS { ACTIVE, SUSPENDED, BLOCKED, RE_ACIVATED }

enum STATUS { PENDING, FAILED, SUCCESS, OTHER }

enum SERVICE_TYPE { WORKSHOP, MOBILE, HYBRID }

enum ITEM_CONDITION { BRAND_NEW, FAIRLY_USED, USED }

enum REPAIR_CLASS {
  FIND_TOW_TRUCK,
  CAR_NOT_STARTING,
  CHANGE_OIL,
  BRAKE_PADS_REPLACEMENT,
  CAR_INSPECTION,
  OVER_HEATING,
  OTHERS
}

enum LOCATION_SELECTION_TYPE { TEXT_ADDRESS, LONGLAT_ADDRESS }

enum DATABASE {
  USERS,
}

enum CREATE_OR_EDIT { EDIT, PREVIEW, CREATE }

enum INFORMATION_TO_EDIT { PHONE, NAME, ADDRES, PHYISICAL, BIO, IMAGE }

enum PAYMENT_TYPE { PRODUCT, DELIVERY, MECHANIC }
